theme: jekyll-theme-minimal
title: Neural Granular Sound Synthesis
description: Additional materials for the submission to ICMC 2020
logo: https://github.com/anonymized124/neural_granular_synthesis/blob/master/figures/architecture.pdf
