theme: jekyll-theme-minimal
title: Neural Granular Sound Synthesis
description: Additional materials for the submission to ICMC 2020
logo: https://raw.github.com/anonymized124/neural_granular_synthesis/raw/master/figures/architecture.pdf
