theme: jekyll-theme-minimal
title: Neural Granular Sound Synthesis
description: Additional materials for the submission to ICMC 2020
logo: https://drive.google.com/file/d/1h77gaY9b5vgFlMNizSStTJrviWExASNe/view?usp=sharing
